name             'minecraft-installer-ubuntu'
maintainer       'Joshua Timberman'
maintainer_email 'cookbooks@housepub.org'
license          'Apache 2.0'
description      'Installs minecraft for ubuntu'
version          '0.3.0'
